FROM odoo:{{ odoo_version }}

{% if apt_dependencies %}
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    {% for dep in apt_dependencies %}
{{ dep }} \
    {% endfor %}
&& rm -rf /var/lib/apt/lists/*
USER odoo
{% endif %}

{% if pip_dependencies %}
{% if pip_dependencies.list %}
RUN pip install --no-cache-dir {{ pip_dependencies.list|join(' ') }}
{% endif %}
{% endif %}

{% if copy_addons %}
USER root
RUN mkdir -p /mnt/copy-addons && chown -R odoo /mnt/copy-addons
USER odoo
{% for addons in copy_addons %}
COPY ./addons/{{ addons.name_hash }} {{ addons.container_posix_path }}
{% endfor %}
{% endif %}
