FROM odoo:{{ odoo_version }}

# Fix for 11.0 Odoo_Version
{% if odoo_version <= 11.0 %}
USER root
RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' \
           -e 's|security.debian.org|archive.debian.org/|g' \
           -e '/stretch-updates/d' /etc/apt/sources.list
RUN rm -rf /etc/apt/sources.list.d/backports.list
{% endif %}

{% if dependencies.apt %}
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    {% for dep in dependencies.apt %}
{{ dep }} \
    {% endfor %}
&& rm -rf /var/lib/apt/lists/*
USER odoo
{% endif %}

{% if dependencies.python %}
{% if dependencies.python.list %}
RUN python3 -m pip install --no-cache-dir {{ dependencies.python.list|join(' ') }}
{% endif %}
{% if dependencies.python.files %}
USER root
RUN mkdir -p {{ dependencies.python.mount_path() }} && chown -R odoo {{ dependencies.python.mount_path() }}
USER odoo
{% for requirment in dependencies.python.files %}
COPY ./requirments/{{ dependencies.python.get_file_hash(requirment) }} {{ dependencies.python.get_file_mount_path(requirment) }}
RUN python3 -m pip install --no-cache-dir -r {{ dependencies.python.get_file_mount_path(requirment) }}
{% endfor %}
USER root
RUN rm -rf {{ dependencies.python.mount_path() }}
USER odoo
{% endif %}
{% endif %}

{% if copy_addons %}
USER root
RUN mkdir -p /mnt/copy-addons && chown -R odoo /mnt/copy-addons
USER odoo
{% for addons in copy_addons %}
COPY ./addons/{{ addons.name_hash }} {{ addons.container_posix_path }}
{% endfor %}
{% endif %}

{% if mount_addons %}
USER root
RUN mkdir -p /mnt/mount-addons && chown -R odoo /mnt/mount-addons
USER odoo
{% endif %}
